name: DisableTrapdoors
version: 1.1.0
main: com.example.disabletrapdoors.DisableTrapdoors
author: VastoriaMC
api-version: 1.21

commands:
  disabletrapdoors:
    description: DisableTrapdoors plugin command
    usage: /disabletrapdoors <reload|list>
    permission: disabletrapdoors.admin
    aliases: [dt]

permissions:
  disabletrapdoors.admin:
    description: Allows use of /disabletrapdoors reload and list
    default: op
  disabletrapdoors.bypass:
    description: Allows interacting with trapdoors in the restricted world
    default: false